### ISSUE TITLE
sticker-sticker.js ERROR

### ISSUE THREAD

**Issue by RavaAchmad** [XM4ZE/XMYULA-MD#14]
```
TypeError: (intermediate value).toBuffer is not a function
    at createSticker (file:///D:/Bot%20Whatsapp/XMYULA-MD-master/XMYULA-MD-master/plugins/sticker-sticker.js?update=1730000477753:56:63)
    at Object.handler (file:///D:/Bot%20Whatsapp/XMYULA-MD-master/XMYULA-MD-master/plugins/sticker-sticker.js?update=1730000477753:20:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.handler (file:///D:/Bot%20Whatsapp/XMYULA-MD-master/XMYULA-MD-master/handler.js?update=1729999050116:1285:6)
```

```
TypeError: text.match is not a function
    at extractUrlFromText (D:\Bot Whatsapp\XMYULA-MD-master\XMYULA-MD-master\node_modules\@adiwajshing\baileys\lib\Utils\messages.js:38:66)
    at generateLinkPreviewIfRequired (D:\Bot Whatsapp\XMYULA-MD-master\XMYULA-MD-master\node_modules\@adiwajshing\baileys\lib\Utils\messages.js:41:48)
    at generateWAMessageContent (D:\Bot Whatsapp\XMYULA-MD-master\XMYULA-MD-master\node_modules\@adiwajshing\baileys\lib\Utils\messages.js:246:71)
    at generateWAMessage (D:\Bot Whatsapp\XMYULA-MD-master\XMYULA-MD-master\node_modules\@adiwajshing\baileys\lib\Utils\messages.js:507:102)
    at Object.sendMessage (D:\Bot Whatsapp\XMYULA-MD-master\XMYULA-MD-master\node_modules\@adiwajshing\baileys\lib\Socket\messages-send.js:621:69)
    at Object.value (file:///D:/Bot%20Whatsapp/XMYULA-MD-master/XMYULA-MD-master/lib/simple.js:542:116)
    at WebMessageInfo.value (file:///D:/Bot%20Whatsapp/XMYULA-MD-master/XMYULA-MD-master/lib/simple.js:1305:35)
    at Object.handler (file:///D:/Bot%20Whatsapp/XMYULA-MD-master/XMYULA-MD-master/plugins/sticker-sticker.js?update=1730000477753:34:5)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.handler (file:///D:/Bot%20Whatsapp/XMYULA-MD-master/XMYULA-MD-master/handler.js?update=1729999050116:1285:6)
```

_[file logs.txt](https://github.com/user-attachments/files/17532681/logs.1.txt)_

**Comment by RavaAchmad** [comment]
@XM4ZE sudah

**Comment by RavaAchmad** [comment]
pakai windows 10

**Comment by RavaAchmad** [comment]
@XM4ZE sudah nemu solusi nya kah? Di hari sebelumnya masih aman dan lancar ga ada kendala di fitur sticker.

**Comment by RavaAchmad** [comment]
tetap saja, mungkin error bagian toBuffer/module nya mungkin.

**Comment by RavaAchmad** [comment]
@XM4ZE Kalo di lihat di log nya awal yang dijalanlan adalah createSticker namun disitu error dan melempar ke bagian akhir jadi mungkin text.match tidak terpengaruh

**Comment by RavaAchmad** [comment]
**closing due to lack of response from author**
